name = "flareact-ingalless"
type = "webpack"
account_id = "7ce246048954beebaa9f69f95f12e827"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
